blog/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views, views_admin
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [

    url(r'^$', views.BlogListView.as_view(), name='blog_list'),

    url(r'^(?P<blog_slug>[\w-]+)/$',
        views.blog_details_view, name='blogdetail'),

    url(r'^category/(?P<blog_category_slug>[\w-]+)/$',
        views.blog_categories_details, name='blog_category_details'),

    url(r'^tag/(?P<blog_tag_slug>[\w-]+)/$',
        views.blog_tag_details, name='blog_tag_details'),

    url(r'^search/item/$',
        views.search, name='search_blog'),


    #################### All ADMIN VIEWS ################################

    ############## BLOG CATEGORY VIEWS ######################

    url(r'^blog/category-list/admin/$', views_admin.BlogCategoriesAdminListView.as_view(), name='blog_category_list'),

    url(r'^blog/category-create/admin/$', views_admin.BlogCategoryCreateView.as_view(), name='blog_category_create'),

    url(r'^blog/category/(?P<blog_category_slug>[\w-]+)/update/admin/$', views_admin.BlogCategoryUpdateView.as_view(), name='blog_category_update'),

    url(r'^blog/category/(?P<blog_category_slug>[\w-]+)/delete/admin/$', views_admin.blog_category_delete_view, name='blog_category_delete'),


    ##################### Blog Views URL ##############################################

    url(r'^blog/list/admin/$', views_admin.BlogListViewAdmin.as_view(), name='blog_list_admin'),

    url(r'^blog/create/admin/$', views_admin.BlogCreateView.as_view(), name='blog_create_admin'),

    url(r'^blog/update/(?P<blog_slug>[\w-]+)/admin/$', views_admin.BlogUpdateView.as_view(), name='blog_update_admin'),

    url(r'^blog/delete/(?P<blog_pk>\d+)/admin/$', views_admin.delete_blog, name='blog_delete_admin'),


    ##################### Blog Tags URL #########################################

    url(r'^blog/tag-list/admin/$', views_admin.BlogTagsListView.as_view(), name='blog_tag_list_admin'),
    url(r'^blog/tag-create/admin/$', views_admin.BlogTagsCreateView.as_view(), name='blog_tag_create_admin'),

    url(r'^blog/tag/(?P<blog_tag_slug>[\w-]+)/update/admin/$', views_admin.BlogTagUpdateView.as_view(), name='blog_tag_update_admin'),

    url(r'^blog//tag/(?P<blog_tag_pk>\d+)/delete/admin/$', views_admin.delete_blog_tags, name='blog_tag_delete_admin'),

]

brown/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls import url, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.index, name='index'),
    path('contact-us', views.contact_us_view, name='contact_us'),

    path('privacy-policy', views.privacy_policy, name='privacy_policy'),

    path('terms-and-conditions', views.terms_conditions, name='terms_conditions'),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r"^our-products/", include("products.urls", namespace="product")),

    url(r"^ecommerce/", include("ecommerce_cart.urls", namespace="ecommerce_cart")),

    url(r"^blogs/", include("blog.urls", namespace="blog")),


    path('superadmin/', views.admin_index, name='admin_index'),
    url(r'^superadmin/contact-query/$', views.contact_query_view, name="contact_query"),
	url(r'^superadmin/contact-query/delete/(?P<query_pk>\d+)/$',
        views.delete_query, name='query_delete'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views, views_admin

app_name = 'products'

urlpatterns = [

    url(r'^list/$',views.all_product_list, name='all_product_list'),
    url(r'^category_wise_product/$',views.search_product_category_wise, name='search_product_category_wise'),

    url(r'^category_product_details/(?P<category_slug>[\w-]+)/$',
        views.product_category_details_view, name='product_category_details'),

    url(r'^(?P<product_slug>[\w-]+)/$',
        views.product_details_view, name='product_detail'),


    ##################### Views Admin #################################

    ######### Product Categories Url  ##################
    # url(r'^category/category-list/$',
    #     views_admin.AllCategoryListView.as_view(), name='category_list'),


    url(r'^product-category/admin/$',
        views_admin.ProductCategoryListView.as_view(), name='category_list'),

    url(r'^product-category/admin/create/$',
        views_admin.ProductCategoryCreateView.as_view(), name='category_create'),

    url(r'^product-category/(?P<category_pk>\d+)/admin/update/$',
        views_admin.ProductCategoryUpdateView.as_view(), name='category_update'),

    url(r'^product-category/(?P<category_pk>\d+)/admin/delete/$',
        views_admin.category_delete_view, name='category_delete'),

    ######### Product Url  ##################

    url(r'^product/admin/$',
        views_admin.ProductsListView.as_view(), name='product_list_admin'),

    url(r'^product/admin/create/$',
        views_admin.ProductCreateView.as_view(), name='product_create'),

    url(r'^product/(?P<product_slug>[\w-]+)/admin/update/$',
        views_admin.ProductUpdateView.as_view(), name='product_update'),

    url(r'^product/(?P<product_slug>[\w-]+)/admin/details/$',
        views_admin.product_details_view, name='product_details_admin'),

    url(r'^product/(?P<product_pk>\d+)/admin/delete/$',
        views_admin.delete_product, name='product_delete'),

]

products/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from django.utils.text import slugify

# Create your models here.

class ProductCategory(models.Model):
    """
    Product Category Model
    """
    name = models.CharField(max_length=200)
    slug = models.SlugField(
		  max_length=200, unique=True, null=True, blank=True)

    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(ProductCategory, self).save(*args, **kwargs)

class Product(models.Model):
    """
    Product Model
    """
    name = models.CharField(max_length=200)
    category = models.ForeignKey(
		  ProductCategory, on_delete=models.CASCADE, related_name='products', null=True)
    image_1 = models.ImageField(
        upload_to='product/product_image_1', null=True, blank=True)
    image_2 = models.ImageField(
        upload_to='product/product_image_2', null=True, blank=True)
    image_3 = models.ImageField(
        upload_to='product/product_image_3', null=True, blank=True)
    original_file = models.FileField(upload_to='product/original_file', null=True, blank=True)
    content_1 = RichTextUploadingField(
		  blank=True, null=True, config_name='special')
    content_2 = RichTextUploadingField(
		  blank=True, null=True, config_name='special')
    content_3 = RichTextUploadingField(
		  blank=True, null=True, config_name='special')
    product_price = models.DecimalField(default=0.00, max_digits=20, decimal_places=2)
    slug = models.SlugField(
        max_length=200, unique=True, null=True, blank=True)
    
    whislist_items = models.ManyToManyField(
		  'user_profile.Customer', related_name='whislist_items', blank=True)

    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

products/forms.py
"""
Forms
"""
from django import forms
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from .models import *



class ProductCategoryForm(forms.ModelForm):
    """
    Product Category Form
    """
    class Meta:
        model = ProductCategory
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super(ProductCategoryForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs = {'class': 'form-control', 'placeholder' : "Enter Product Category Name"}
        

# class ProductTagForm(forms.ModelForm):
#     """
#     Product Tags Form
#     """
#     class Meta:
#         model = ProductTags
#         fields = ('name',)

#     def __init__(self, *args, **kwargs):
#         super(ProductTagForm, self).__init__(*args, **kwargs)

#         self.fields['name'].widget.attrs = {'class': 'form-control', 'placeholder' : "Enter Product Tag Name"}



class ProductsForm(forms.ModelForm):
    """
    Product From
    """
    class Meta:
        model = Product
        fields = ('name','category','image_1','image_2','image_3','content_1','content_2','content_3','product_price','original_file')

    def __init__(self, *args, **kwargs):
        super(ProductsForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs = {'class': 'form-control', 'placeholder' : "Enter Product Name"}
        self.fields['category'].widget.attrs = {'class': 'select2_demo_2 form-control',}
        
        
        self.fields['product_price'].widget.attrs = {'class': 'form-control', 'placeholder' : "Enter MRP Price"}


        self.fields['image_1'].widget.attrs = {'class': 'form-control',}
        self.fields['image_2'].widget.attrs = {'class': 'form-control',}
        self.fields['image_3'].widget.attrs = {'class': 'form-control',}
        self.fields['original_file'].widget.attrs = {'class': 'form-control',}


    def clean_name(self):
        """
        Clean function to raise Validation Error if Product Name already exist in a company.
        """
        name = self.cleaned_data['name']
        master_id = 0

        if self.instance:
            # master id is used to exclude current master so that it is not checked as duplicate
            master_id = self.instance.id

        if Product.objects.filter(name__iexact=name).exclude(id=master_id).exists():
            raise forms.ValidationError("This Product already exists!")
        return name

products/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import *
from app.common import *
# Create your views here.


def all_product_list(request):
	"""
		All Product List View
	"""
	products = Product.objects.all().order_by('-id')
	
	page = request.GET.get('page', 1)

	paginator = Paginator(products, 16)
	try:
		product_list = paginator.page(page)
	except PageNotAnInteger:
		product_list = paginator.page(1)
	except EmptyPage:
		product_list = paginator.page(paginator.num_pages)

	category_list = ProductCategory.objects.all().order_by('-id')

	all_product_count = Product.objects.all().count()

	print(category_list)

	context = {
		'product_list' : product_list,
		'category_list' : category_list,
		'all_product_count' : all_product_count
	}
	return CommonMixin.render(request, 'product_list.html', context)


def product_category_details_view(request, category_slug):
	"""
	Product Category Deatils
	"""
	category_details = ProductCategory.objects.filter(slug=category_slug).first()

	products = Product.objects.filter(category=category_details).order_by('id')
	

	page = request.GET.get('page', 1)

	paginator = Paginator(products, 16)
	try:
		product_list = paginator.page(page)
	except PageNotAnInteger:
		product_list = paginator.page(1)
	except EmptyPage:
		product_list = paginator.page(paginator.num_pages)

	category_list = ProductCategory.objects.all().order_by('id')

	context = {
		'category_details' : category_details,
		'product_list' : product_list,
		'category_list' : category_list
	}
	return CommonMixin.render(request, 'product_category_details.html', context)


def search_product_category_wise(request):
	"""
	Search Product Category Wise
	"""
	category_slug = request.GET.get('q')


	if category_slug == 'all':

		return redirect(reverse('product:all_product_list'))

	else:
		category_details = ProductCategory.objects.filter(slug=category_slug).first()

		products = Product.objects.filter(category=category_details).order_by('-id')
	

	page = request.GET.get('page', 1)

	paginator = Paginator(products, 16)
	try:
		product_list = paginator.page(page)
	except PageNotAnInteger:
		product_list = paginator.page(1)
	except EmptyPage:
		product_list = paginator.page(paginator.num_pages)

	category_list = ProductCategory.objects.all().exclude(id=category_details.id).order_by('id')

	context = {
		'category_details' : category_details,
		'product_list' : product_list,
		'category_list' : category_list
	}
	return CommonMixin.render(request, 'product_category_details.html', context)


def product_details_view(request, product_slug):
	"""
	Product Details View
	"""
	product_details = Product.objects.filter(slug=product_slug).first()

	context = {
		'product_details' : product_details
	}
	return CommonMixin.render(request, 'product_details.html', context)

products/templates/product_admin/category_list.html
{% extends "metronics/base.html" %}
{% load static %}

{% load mathfilters %}
{% load humanize %}
{% load l10n %}
{% load poll_extras %}

{% block title %} Product Category List {% endblock %}

{% block content %}
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-2">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Product Category List</h5>
                <!--end::Page Title-->

                <!--begin::Actions-->
                <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                <!-- <span class="text-muted font-weight-bold mr-4">#XRS-45670</span>
				<a href="#" class="btn btn-light-warning font-weight-bolder btn-sm">Add New</a> -->
                <!--end::Actions-->

                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="{% url 'admin_index' %}" class="text-muted">Admin Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#" class="text-muted">Product Category List</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->



            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                <!--begin::Actions-->
                <!-- <a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Today</a>
				<a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Month</a>
				<a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Year</a> -->
                <!--end::Actions-->
                <!--begin::Daterange-->
                <a href="#" class="btn btn-sm btn-light font-weight-bold mr-2" data-toggle="tooltip"
                    data-placement="left">
                    <span class="text-muted font-size-base font-weight-bold mr-2"
                        id="kt_dashboard_daterangepicker_title">Today</span>
                    <span class="text-primary font-size-base font-weight-bolder"
                        id="kt_dashboard_daterangepicker_date">{% now "jS F Y" %}</span>
                </a>
                <!--end::Daterange-->

            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-md-12">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b">
                        <div class="card-header">
                            <div class="card-title">
                                <h3 class="card-label">All Product Categories</h3>
                            </div>
                            <div class="card-title pull-right">
                                <a href="{% url 'product:category_create' %}" class="btn btn-success"><i class="ki ki-plus"></i> Add Categories</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <!--begin::Example-->
                            <div class="example mb-10">
                                <div class="example-preview">
                                    <table class="table">
                                        <thead class="thead-light">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Category Name</th>
                                                <th scope="col">Update</th>
                                                <th scope="col">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in category_list %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ item.name }}</td>
                                                <td><a href="{% url 'product:category_update' category_pk=item.pk %}" class='btn btn-warning'><i class="ki ki-reload"></i></a></td>
                                                <td><a href="{% url 'product:category_delete' category_pk=item.pk %}" class='btn btn-danger' onclick="return confirm('Are you sure you want to remove this category?');"><i class="far fa-trash-alt"></i></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!--end::Example-->
                        </div>
                    </div>
                    <!--end::Card-->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

products/templates/product_admin/product_list.html
{% extends "metronics/base.html" %} {% load static %} {% load mathfilters %} {% load humanize %} {% load l10n %} {% load poll_extras %} {% block title %} Products List {% endblock %} {% block content %}
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-2">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Products List</h5>
                <!--end::Page Title-->

                <!--begin::Actions-->
                <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                <!-- <span class="text-muted font-weight-bold mr-4">#XRS-45670</span>
				<a href="#" class="btn btn-light-warning font-weight-bolder btn-sm">Add New</a> -->
                <!--end::Actions-->

                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="{% url 'admin_index' %}" class="text-muted">Admin Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#" class="text-muted">Products List</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->



            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                <!--begin::Actions-->
                <!-- <a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Today</a>
				<a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Month</a>
				<a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Year</a> -->
                <!--end::Actions-->
                <!--begin::Daterange-->
                <a href="#" class="btn btn-sm btn-light font-weight-bold mr-2" data-toggle="tooltip" data-placement="left">
                    <span class="text-muted font-size-base font-weight-bold mr-2" id="kt_dashboard_daterangepicker_title">Today</span>
                    <span class="text-primary font-size-base font-weight-bolder" id="kt_dashboard_daterangepicker_date">{% now "jS F Y" %}</span>
                </a>
                <!--end::Daterange-->

            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->
    
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-md-12">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b">
                        <div class="card-header">
                            <div class="card-title">
                                <h3 class="card-label">All Products</h3>
                            </div>
                            <div class="card-title pull-right">
                                <a href="{% url 'product:product_create' %}" class="btn btn-success"><i
                                        class="ki ki-plus"></i> Add Products</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <!--begin::Example-->
                            <div class="example mb-10">
                                <div class="example-preview">
                                    <table class="table">
                                        <thead class="thead-light">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Product Name</th>
                                                <th scope="col">Under Category</th>
                                                <th scope="col">Product Price</th>
                                                <th scope="col">View Product</th>
                                                <th scope="col">Update</th>
                                                <th scope="col">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in product_list %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter0|add:page_obj.start_index }}</th>
                                                <td>{{ item.name }}</td>
                                                <td>{{ item.category.name }}</td>
                                                <td>$ {{ item.product_price }}</td>
                                                <td><a href="{% url 'product:product_details_admin' product_slug=item.slug %}" class='btn btn-success'><i class="flaticon-eye"></i></a></td>
                                                <td><a href="{% url 'product:product_update' product_slug=item.slug %}" class='btn btn-warning'><i class="ki ki-reload"></i></a></td>
                                                <td><a href="{% url 'product:product_delete' product_pk=item.pk %}" class='btn btn-danger' onclick="return confirm('Are you sure you want to remove this category?');"><i
                                                            class="far fa-trash-alt"></i></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!--end::Example-->

                            {% if is_paginated %}
                            <nav aria-label="...">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link"
                                            href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                                    </li>
                                    {% endif %}

                                    {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                                    </li>
                                    {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                    {% endfor %}


                                    {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Next</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>
                            {% endif %}
                        </div>
                    </div>
                    <!--end::Card-->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}