blog/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views, views_admin
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [

    url(r'^$', views.BlogListView.as_view(), name='blog_list'),

    url(r'^(?P<blog_slug>[\w-]+)/$',
        views.blog_details_view, name='blogdetail'),

    url(r'^category/(?P<blog_category_slug>[\w-]+)/$',
        views.blog_categories_details, name='blog_category_details'),

    url(r'^tag/(?P<blog_tag_slug>[\w-]+)/$',
        views.blog_tag_details, name='blog_tag_details'),

    url(r'^search/item/$',
        views.search, name='search_blog'),


    #################### All ADMIN VIEWS ################################

    ############## BLOG CATEGORY VIEWS ######################

    url(r'^blog/category-list/admin/$', views_admin.BlogCategoriesAdminListView.as_view(), name='blog_category_list'),

    url(r'^blog/category-create/admin/$', views_admin.BlogCategoryCreateView.as_view(), name='blog_category_create'),

    url(r'^blog/category/(?P<blog_category_slug>[\w-]+)/update/admin/$', views_admin.BlogCategoryUpdateView.as_view(), name='blog_category_update'),

    url(r'^blog/category/(?P<blog_category_slug>[\w-]+)/delete/admin/$', views_admin.blog_category_delete_view, name='blog_category_delete'),


    ##################### Blog Views URL ##############################################

    url(r'^blog/list/admin/$', views_admin.BlogListViewAdmin.as_view(), name='blog_list_admin'),

    url(r'^blog/create/admin/$', views_admin.BlogCreateView.as_view(), name='blog_create_admin'),

    url(r'^blog/update/(?P<blog_slug>[\w-]+)/admin/$', views_admin.BlogUpdateView.as_view(), name='blog_update_admin'),

    url(r'^blog/delete/(?P<blog_pk>\d+)/admin/$', views_admin.delete_blog, name='blog_delete_admin'),


    ##################### Blog Tags URL #########################################

    url(r'^blog/tag-list/admin/$', views_admin.BlogTagsListView.as_view(), name='blog_tag_list_admin'),
    url(r'^blog/tag-create/admin/$', views_admin.BlogTagsCreateView.as_view(), name='blog_tag_create_admin'),

    url(r'^blog/tag/(?P<blog_tag_slug>[\w-]+)/update/admin/$', views_admin.BlogTagUpdateView.as_view(), name='blog_tag_update_admin'),

    url(r'^blog//tag/(?P<blog_tag_pk>\d+)/delete/admin/$', views_admin.delete_blog_tags, name='blog_tag_delete_admin'),

]

brown/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls import url, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.index, name='index'),
    path('contact-us', views.contact_us_view, name='contact_us'),

    path('privacy-policy', views.privacy_policy, name='privacy_policy'),

    path('terms-and-conditions', views.terms_conditions, name='terms_conditions'),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r"^our-products/", include("products.urls", namespace="product")),

    url(r"^ecommerce/", include("ecommerce_cart.urls", namespace="ecommerce_cart")),

    url(r"^blogs/", include("blog.urls", namespace="blog")),


    path('superadmin/', views.admin_index, name='admin_index'),
    url(r'^superadmin/contact-query/$', views.contact_query_view, name="contact_query"),
	url(r'^superadmin/contact-query/delete/(?P<query_pk>\d+)/$',
        views.delete_query, name='query_delete'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from PIL import Image
import sys
import os
from io import BytesIO

from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.files.uploadedfile import InMemoryUploadedFile
# Create your models here.


class BlogTags(models.Model):
    """
    Blog Tags Model
    """
    name = models.CharField(max_length=200)
    slug = models.SlugField(
        max_length=200, unique=True, null=True, blank=True)

    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(BlogTags, self).save(*args, **kwargs)


class BlogCategories(models.Model):
    """
    Blog Categories
    """
    title = models.CharField(max_length=40, default='Uncategorized')
    slug = models.SlugField(
        max_length=200, unique=True, null=True, blank=True)

    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Returns absolute url for a blog categories
        """
        return reverse("blog:blog_category_details", kwargs={'blog_category_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogCategories, self).save(*args, **kwargs)


class Blog(models.Model):
    """
    Blog Model
    """
    date = models.DateTimeField(auto_now_add=True)
    post_date = models.DateField(blank=True)
    blog_title = models.CharField(max_length=255, unique=True)
    description = RichTextUploadingField(
        blank=True, null=True, config_name='special')
    blog_image = models.ImageField(
        upload_to='blog_image', null=True, blank=True, help_text='Image Size 450 x 277')
    category = models.ForeignKey(
        BlogCategories, on_delete=models.CASCADE, related_name='blogs')
    tags = models.ManyToManyField(
        BlogTags, related_name='blog_tags', blank=True)
    slug = models.SlugField(
        max_length=255, unique=True, null=True, blank=True)

    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.blog_title

    def get_absolute_url(self):
        """
        Returns absolute url for a blog categories
        """
        return reverse("blog:blogdetail", kwargs={'blog_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.blog_title)

        if self.blog_image:
            temp_image = Image.open(self.blog_image).convert('RGB')
            output_io_stream = BytesIO()
            temp_resized_image = temp_image.resize((800, 800))
            temp_resized_image.save(
                output_io_stream, format='JPEG', quality=90)
            output_io_stream.seek(0)
            self.blog_image = InMemoryUploadedFile(output_io_stream,
                                                    'ImageField', "%s.jpg" % self.blog_image.name.split('.')[0], 'image/jpeg', sys.getsizeof(output_io_stream), None)

        super(Blog, self).save(*args, **kwargs)


class BlogComments(models.Model):
    """
    Blog Comments Model
    """ 
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    comment = models.TextField()
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='blogs_comment')


    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.name

blog/forms.py
"""
Forms
"""
from django import forms

from blog.models import BlogCategories, Blog, BlogComments, BlogTags

class DateInput(forms.DateInput):
    """
    Widgets support for date input
    """
    input_type = 'date'

class BlogCategoriesForm(forms.ModelForm):
    """
    Blog Category Form
    """
    class Meta:
        model = BlogCategories
        fields = ['title']

    def __init__(self, *args, **kwargs):
        super(BlogCategoriesForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs = {
            'class' : 'form-control','placeholder' : 'Blog Category Name', }


class BlogForm(forms.ModelForm):
    """
    Blog Forms
    """
    class Meta:
        model = Blog
        fields = ['blog_title','description','blog_image','category','tags','post_date']
        widgets = {
            'post_date': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super(BlogForm, self).__init__(*args, **kwargs)
        self.fields['blog_title'].widget.attrs = {
            'class' : 'form-control','placeholder' : 'Blog Title', }
        self.fields['blog_image'].widget.attrs = {
            'class' : 'form-control',}
        self.fields['category'].widget.attrs = {
            'class': 'select2_demo_2 form-control', }
        self.fields['tags'].widget.attrs = {
            'class': 'select2_demo_3 form-control','multiple' : 'multiple', }
        self.fields['post_date'].widget.attrs = {
            'class' : 'form-control',}

class BlogTagsForm(forms.ModelForm):
    """
    Blog Tags Form
    """
    class Meta:
        model = BlogTags
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super(BlogTagsForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs = {
            'class' : 'form-control','placeholder' : 'Blog Tag Name', }


class BlogCommentsForm(forms.ModelForm):
    """
    BlogComments Form
    """
    class Meta:
        model = BlogComments
        fields = ['name', 'comment']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from app.common import CommonMixin
from products.models import Product

from .models import BlogCategories, Blog, BlogComments, BlogTags
from .forms import BlogCommentsForm
# Create your views here.


class BlogListView(CommonMixin, ListView):
    """
    Blog List View
    """
    model = Blog
    context_object_name = 'blog_list'
    template_name = 'blog_list.html'
    paginate_by = 6

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)

        context['blog_categories'] = BlogCategories.objects.all().order_by('title')
        context['latest_blogs'] = Blog.objects.all().order_by('-id')[:3]
        context['blog_tags'] = BlogTags.objects.all().order_by('id')

        return context

def blog_details_view(request, blog_slug):
    """
    Blog Details View
    """
    blog_details = Blog.objects.filter(slug=blog_slug).first()

    blog_categories = BlogCategories.objects.all().order_by('title')

    comment_list = BlogComments.objects.filter(
        blog=blog_details).order_by('-id')[:10]

    tag_list = BlogTags.objects.all().order_by('-id')

    recent_blogs = Blog.objects.all().order_by('-id')[:3]

    related_blogs = Blog.objects.filter(category=blog_details.category).exclude(
        id=blog_details.id)[:2]

    recent_comments = BlogComments.objects.filter(blog=blog_details).order_by('-id')[:6]

    if request.method == "POST":
        comment_form = BlogCommentsForm(request.POST or None)
        if comment_form.is_valid():
            name = request.POST.get('name')
            comment = request.POST.get('comment')
            answer = BlogComments.objects.create(
                name=name, comment=comment, blog=blog_details)
            answer.save()
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    else:
        comment_form = BlogCommentsForm()

    product_list = Product.objects.all().order_by('id')[:5]

    context = {

        'blog_details': blog_details,
        'comment_list': comment_list,
        'blog_categories': blog_categories,
        'form': comment_form,
        'tag_list': tag_list,
        'related_blogs' : related_blogs,
        'recent_blogs': recent_blogs,
        'recent_comments': recent_comments,
        'product_list' : product_list
    }
    return CommonMixin.render(request, 'blog_details.html', context)

def blog_categories_details(request, blog_category_slug):
    """
    Blog Category detail view
    """
    category_details = BlogCategories.objects.filter(
        slug=blog_category_slug).first()

    blogs = Blog.objects.filter(category=category_details).order_by('-id')

    page = request.GET.get('page', 1)

    paginator = Paginator(blogs, 6)
    try:
        blog_list = paginator.page(page)
    except PageNotAnInteger:
        blog_list = paginator.page(1)
    except EmptyPage:
        blog_list = paginator.page(paginator.num_pages)

    blog_categories = BlogCategories.objects.all().exclude(
        id=category_details.id).order_by('title')

    latest_blogs = Blog.objects.all().order_by('id')[:3]

    blog_tags = BlogTags.objects.all().order_by('id')

    context = {
        'category_details': category_details,
        'blog_list': blog_list,
        'blog_categories': blog_categories,
        'latest_blogs': latest_blogs,
        'blog_tags': blog_tags
    }
    return CommonMixin.render(request, 'blog_category_details.html', context)


def blog_tag_details(request, blog_tag_slug):
    """
    Blog Tag Detail View
    """
    blog_tag_details = BlogTags.objects.filter(slug=blog_tag_slug).first()

    blog_list = blog_tag_details.blog_tags.all()

    page = request.GET.get('page', 1)

    paginator = Paginator(blog_list, 6)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    blog_categories = BlogCategories.objects.all().order_by('title')
    latest_blogs = Blog.objects.all().order_by('id')[:3]
    blog_tags = BlogTags.objects.all().exclude(
        id=blog_tag_details.id).order_by('id')

    context = {

        'blog_tag_details': blog_tag_details,
        'blog_list': blogs,
        'blog_categories': blog_categories,
        'latest_blogs': latest_blogs,
        'blog_tags': blog_tags
    }
    return CommonMixin.render(request, 'blog_tag_details.html', context)


def search(request):
    """
    Search View
    """
    template = 'search_blog_list.html'

    query = request.GET.get('q')

    if query:
        result = Blog.objects.filter(Q(blog_title__icontains=query) | Q(
            description__icontains=query) | Q(category__title__icontains=query))
    else:
        result = Blog.objects.none()

    page = request.GET.get('page', 1)

    paginator = Paginator(result, 6)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    blog_categories = BlogCategories.objects.all().order_by('title')
    latest_blogs = Blog.objects.all().order_by('id')[:3]
    blog_tags = BlogTags.objects.all().order_by('id')

    context = {
        'search_result': query,
        'blog_list': blogs,
        'blog_categories': blog_categories,
        'latest_blogs': latest_blogs,
        'blog_tags': blog_tags
    }

    return CommonMixin.render(request, template, context)

blog/templates/blog_admin/blog_category_list.html
{% extends "metronics/base.html" %}
{% load static %}

{% load mathfilters %}
{% load humanize %}
{% load l10n %}
{% load poll_extras %}

{% block title %} Blog Category List {% endblock %}

{% block content %}
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-2">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Brownfold Blog Category List</h5>
                <!--end::Page Title-->

                <!--begin::Actions-->
                <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                <!-- <span class="text-muted font-weight-bold mr-4">#XRS-45670</span>
				<a href="#" class="btn btn-light-warning font-weight-bolder btn-sm">Add New</a> -->
                <!--end::Actions-->

                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="{% url 'admin_index' %}" class="text-muted">Admin Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#" class="text-muted">Brownfold Blog Category List</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->



            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                <!--begin::Actions-->
                <!-- <a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Today</a>
				<a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Month</a>
				<a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Year</a> -->
                <!--end::Actions-->
                <!--begin::Daterange-->
                <a href="#" class="btn btn-sm btn-light font-weight-bold mr-2" data-toggle="tooltip"
                    data-placement="left">
                    <span class="text-muted font-size-base font-weight-bold mr-2"
                        id="kt_dashboard_daterangepicker_title">Today</span>
                    <span class="text-primary font-size-base font-weight-bolder"
                        id="kt_dashboard_daterangepicker_date">{% now "jS F Y" %}</span>
                </a>
                <!--end::Daterange-->

            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-md-12">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b">
                        <div class="card-header">
                            <div class="card-title">
                                <h3 class="card-label">Brownfold Blog Category List</h3>
                            </div>
                            <div class="card-title pull-right">
                                <a href="{% url 'blog:blog_category_create' %}" class="btn btn-success"><i class="ki ki-plus"></i> Add Categories</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <!--begin::Example-->
                            <div class="example mb-10">
                                <div class="example-preview">
                                    <table class="table">
                                        <thead class="thead-light">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Category Name</th>
                                                <th scope="col">Update</th>
                                                <th scope="col">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in blog_category_list %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ item.title }}</td>
                                                <td><a href="{% url 'blog:blog_category_update' blog_category_slug=item.slug %}" class='btn btn-warning'><i class="ki ki-reload"></i></a></td>
                                                <td><a href="{% url 'blog:blog_category_delete' blog_category_slug=item.slug %}" class='btn btn-danger' onclick="return confirm('Are you sure you want to remove this category?');"><i class="far fa-trash-alt"></i></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!--end::Example-->

                            {% if is_paginated %}
                            <nav aria-label="...">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link"
                                            href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                                    </li>
                                    {% endif %}

                                    {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                                    </li>
                                    {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                    {% endfor %}


                                    {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Next</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>
                            {% endif %}
                        </div>
                    </div>
                    <!--end::Card-->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog_admin/blog_list.html
{% extends "metronics/base.html" %}
{% load static %}

{% load mathfilters %}
{% load humanize %}
{% load l10n %}
{% load poll_extras %}

{% block title %} Brownfold Blog Category List {% endblock %}

{% block content %}
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-2">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Brownfold Blog Category List</h5>
                <!--end::Page Title-->

                <!--begin::Actions-->
                <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                <!-- <span class="text-muted font-weight-bold mr-4">#XRS-45670</span>
				<a href="#" class="btn btn-light-warning font-weight-bolder btn-sm">Add New</a> -->
                <!--end::Actions-->

                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="{% url 'admin_index' %}" class="text-muted">Admin Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#" class="text-muted">Brownfold Blog Category List</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->



            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                <!--begin::Actions-->
                <!-- <a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Today</a>
				<a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Month</a>
				<a href="#" class="btn btn-clean btn-sm font-weight-bold font-size-base mr-1">Year</a> -->
                <!--end::Actions-->
                <!--begin::Daterange-->
                <a href="#" class="btn btn-sm btn-light font-weight-bold mr-2" data-toggle="tooltip"
                    data-placement="left">
                    <span class="text-muted font-size-base font-weight-bold mr-2"
                        id="kt_dashboard_daterangepicker_title">Today</span>
                    <span class="text-primary font-size-base font-weight-bolder"
                        id="kt_dashboard_daterangepicker_date">{% now "jS F Y" %}</span>
                </a>
                <!--end::Daterange-->

            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-md-12">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b">
                        <div class="card-header">
                            <div class="card-title">
                                <h3 class="card-label">Brownfold Blog Category List</h3>
                            </div>
                            <div class="card-title pull-right">
                                <a href="{% url 'blog:blog_create_admin' %}" class="btn btn-success"><i class="ki ki-plus"></i> Add Blogs</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <!--begin::Example-->
                            <div class="example mb-10">
                                <div class="example-preview">
                                    <table class="table">
                                        <thead class="thead-light">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Blog Title</th>
                                                <th scope="col">Blog Category</th>
                                                <th scope="col">Blog Date</th>
                                                <th scope="col">View On Site</th>
                                                <th scope="col">Update</th>
                                                <th scope="col">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in blog_list %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ item.blog_title }}</td>
                                                <td>{{ item.category }}</td>
                                                <td>{{ item.post_date }}</td>
                                                <td><a href="{% url 'blog:blogdetail' blog_slug=item.slug %}" class='btn btn-success' target="__blank"><i class="fa fa-eye" aria-hidden="true"></i></a></td>
                                                <td><a href="{% url 'blog:blog_update_admin' blog_slug=item.slug %}" class='btn btn-warning'><i class="ki ki-reload"></i></a></td>
                                                <td><a href="{% url 'blog:blog_delete_admin' blog_pk=item.pk %}" class='btn btn-danger' onclick="return confirm('Are you sure you want to remove this blog?');"><i class="far fa-trash-alt"></i></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!--end::Example-->

                            {% if is_paginated %}
                            <nav aria-label="...">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link"
                                            href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                                    </li>
                                    {% endif %}

                                    {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                                    </li>
                                    {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                    {% endfor %}


                                    {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Next</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>
                            {% endif %}
                        </div>
                    </div>
                    <!--end::Card-->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}