blog/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views, views_admin
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [

    url(r'^$', views.BlogListView.as_view(), name='blog_list'),

    url(r'^(?P<blog_slug>[\w-]+)/$',
        views.blog_details_view, name='blogdetail'),

    url(r'^category/(?P<blog_category_slug>[\w-]+)/$',
        views.blog_categories_details, name='blog_category_details'),

    url(r'^tag/(?P<blog_tag_slug>[\w-]+)/$',
        views.blog_tag_details, name='blog_tag_details'),

    url(r'^search/item/$',
        views.search, name='search_blog'),


    #################### All ADMIN VIEWS ################################

    ############## BLOG CATEGORY VIEWS ######################

    url(r'^blog/category-list/admin/$', views_admin.BlogCategoriesAdminListView.as_view(), name='blog_category_list'),

    url(r'^blog/category-create/admin/$', views_admin.BlogCategoryCreateView.as_view(), name='blog_category_create'),

    url(r'^blog/category/(?P<blog_category_slug>[\w-]+)/update/admin/$', views_admin.BlogCategoryUpdateView.as_view(), name='blog_category_update'),

    url(r'^blog/category/(?P<blog_category_slug>[\w-]+)/delete/admin/$', views_admin.blog_category_delete_view, name='blog_category_delete'),


    ##################### Blog Views URL ##############################################

    url(r'^blog/list/admin/$', views_admin.BlogListViewAdmin.as_view(), name='blog_list_admin'),

    url(r'^blog/create/admin/$', views_admin.BlogCreateView.as_view(), name='blog_create_admin'),

    url(r'^blog/update/(?P<blog_slug>[\w-]+)/admin/$', views_admin.BlogUpdateView.as_view(), name='blog_update_admin'),

    url(r'^blog/delete/(?P<blog_pk>\d+)/admin/$', views_admin.delete_blog, name='blog_delete_admin'),


    ##################### Blog Tags URL #########################################

    url(r'^blog/tag-list/admin/$', views_admin.BlogTagsListView.as_view(), name='blog_tag_list_admin'),
    url(r'^blog/tag-create/admin/$', views_admin.BlogTagsCreateView.as_view(), name='blog_tag_create_admin'),

    url(r'^blog/tag/(?P<blog_tag_slug>[\w-]+)/update/admin/$', views_admin.BlogTagUpdateView.as_view(), name='blog_tag_update_admin'),

    url(r'^blog//tag/(?P<blog_tag_pk>\d+)/delete/admin/$', views_admin.delete_blog_tags, name='blog_tag_delete_admin'),

]

brown/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls import url, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.index, name='index'),
    path('contact-us', views.contact_us_view, name='contact_us'),

    path('privacy-policy', views.privacy_policy, name='privacy_policy'),

    path('terms-and-conditions', views.terms_conditions, name='terms_conditions'),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r"^our-products/", include("products.urls", namespace="product")),

    url(r"^ecommerce/", include("ecommerce_cart.urls", namespace="ecommerce_cart")),

    url(r"^blogs/", include("blog.urls", namespace="blog")),


    path('superadmin/', views.admin_index, name='admin_index'),
    url(r'^superadmin/contact-query/$', views.contact_query_view, name="contact_query"),
	url(r'^superadmin/contact-query/delete/(?P<query_pk>\d+)/$',
        views.delete_query, name='query_delete'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce_cart/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

app_name = 'ecommerce_cart'

urlpatterns = [
    url(r'^whislist/$', views.whislist_view, name='whislist_view'),

    url(r'^add-to-whislist/(?P<product_id>[-\w]+)/$',
        views.add_to_whislist, name="add_to_whislist"),

    url(r'^remove-from-whislist/(?P<product_id>[-\w]+)/$',
        views.remove_from_whislist, name="remove_from_whislist"),

    url(r'^add-to-cart/(?P<product_id>[-\w]+)/$',
        views.add_to_cart, name="add_to_cart"),

    url(r'^remove-from-cart/(?P<item_id>[-\w]+)/$',
        views.delete_from_cart, name="remove-from-cart"),

    url(r'^checkout/$', views.check_out_address, name='check_out_address'),

    url(r'^checkout/confirm/$', views.checkout_confirm_page, name='checkout_confirm_page'),

    url(r'^cart/page/$', views.cart_view, name='cart_view'),

    url(r'^cart/add/ajax/$', views.add_to_cart_ajax, name='add_to_cart_ajax'),

    url(r'^whislist/remove/ajax/$', views.remove_from_whislist_ajax, name='remove_from_whislist_ajax'),


    ##### Admin Urls #####

    url(r'^orders_list/admin/$',
        views.UserOrderListAdminView.as_view(), name='orders_list_admin'),

    url(r'^orders/(?P<user_order_pk>\d+)/admin/$',
        views.OrderDetailView.as_view(), name='orders_details_admin'),
]

products/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views, views_admin

app_name = 'products'

urlpatterns = [

    url(r'^list/$',views.all_product_list, name='all_product_list'),
    url(r'^category_wise_product/$',views.search_product_category_wise, name='search_product_category_wise'),

    url(r'^category_product_details/(?P<category_slug>[\w-]+)/$',
        views.product_category_details_view, name='product_category_details'),

    url(r'^(?P<product_slug>[\w-]+)/$',
        views.product_details_view, name='product_detail'),


    ##################### Views Admin #################################

    ######### Product Categories Url  ##################
    # url(r'^category/category-list/$',
    #     views_admin.AllCategoryListView.as_view(), name='category_list'),


    url(r'^product-category/admin/$',
        views_admin.ProductCategoryListView.as_view(), name='category_list'),

    url(r'^product-category/admin/create/$',
        views_admin.ProductCategoryCreateView.as_view(), name='category_create'),

    url(r'^product-category/(?P<category_pk>\d+)/admin/update/$',
        views_admin.ProductCategoryUpdateView.as_view(), name='category_update'),

    url(r'^product-category/(?P<category_pk>\d+)/admin/delete/$',
        views_admin.category_delete_view, name='category_delete'),

    ######### Product Url  ##################

    url(r'^product/admin/$',
        views_admin.ProductsListView.as_view(), name='product_list_admin'),

    url(r'^product/admin/create/$',
        views_admin.ProductCreateView.as_view(), name='product_create'),

    url(r'^product/(?P<product_slug>[\w-]+)/admin/update/$',
        views_admin.ProductUpdateView.as_view(), name='product_update'),

    url(r'^product/(?P<product_slug>[\w-]+)/admin/details/$',
        views_admin.product_details_view, name='product_details_admin'),

    url(r'^product/(?P<product_pk>\d+)/admin/delete/$',
        views_admin.delete_product, name='product_delete'),

]

templates/base_2.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/16.png' %}">

    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- styles -->
    <link rel="stylesheet" href="{% static 'assets/css/blog.css' %}">

    {% block css %}

    {% endblock %}
    
  </head>
  <body class="" style="overflow-x: hidden;">
    <!-- header -->
    <header>
        <a href="/" class="logoWrapper">
          <img src="{% static 'assets/images/Logo.svg' %}" alt="logo" class="svg" />
        </a>
        <div class="actionBtnWrapper">
          <a href="{% url 'ecommerce_cart:whislist_view' %}" class="wishlistTrigger">
            <img src="{% static 'assets/d44acf32/img/Favoritemenu.svg' %}" class="svg stroke" />
          </a>
          <!--        <a href="#">-->
          <!--            <img src="--><!--/img/template.svg" class="svg stroke">-->
          <!--        </a>-->
          <a href="{% url 'ecommerce_cart:cart_view' %}" class="cartTrigger">
            <img src="{% static 'assets/d44acf32/img/bag.svg' %}" class="svg" />
            <span class="counter"></span>
          </a>
          <a href="#" class="menuTrigger">
            <img src="{% static 'assets/d44acf32/img/menu.svg' %}" class="svg stroke" />
          </a>
        </div>
      </header>
    <!-- end -->
    <!-- section 1 -->
    {% block content %}

    {% endblock %}
    <!-- end -->
    <!-- section 5 -->
    <section id="section_5">
      <div class="container">
        <div class="row text-center">
          <div class="col-sm-12 col-md-12 col-lg-12 text-yellow mrb_1">
            <span>LET'S CONNECT</span>
          </div>
          <div class="col-sm-12 col-md-12 col-lg-12 text-yellow mrb_1">
            <span class="h5">LET'S SUPERCHARGE YOUR DESIGN PROCESS</span>
          </div>
          <div class="col-sm-12 col-md-12 col-lg-12 text-white mrb_1">
            <span>have unanswered questions? book a live demo to get a white-glove walkthrough of the process and the platform</span>
          </div>
          <div class="col-sm-12 col-md-12 col-lg-12 text-white mrb_1">
              <button type="button" class="btn btn-outline-primary rounded-pill button-hover-none">BOOK A CONSULTATION</button>
          </div>
        </div>
      </div>
    </section>
    <!-- end -->
    <!-- footer -->
    <section id="footer">
      <footer class="container">
        <nav class="navbar navbar-expand-lg">
          <div class="container-fluid">
              <a class="navbar-brand" href="#">
                  <img src="{% static 'assets/img_new/Logo_yellow.svg' %}" alt="" width="30" height="24"> <span class="text-white">BROWNFOLD © 2023. ALL RIGHTS RESERVED.</span>
                </a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              </ul>
              <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link text-yellow" href="{% url 'product:all_product_list' %}">marketplace</a>
                  </li>
                  
                  <li class="nav-item">
                    <a class="nav-link text-yellow" href="{% url 'contact_us' %}">contact</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-yellow" href="#"><i class="fa-brands fa-twitter"></i></i></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-yellow" href="#"><i class="fa-brands fa-instagram"></i></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-yellow" href="#"><i class="fa-brands fa-facebook"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </nav>
      </footer>
    </section>


    <div class="menu" {% if request.user_agent.is_mobile %} style="background: #fde722;" {% else %} style="background: url({% static 'assets/product_backgroung.png' %}) repeat-x; background-size: cover;"  {% endif %}>
        <div class="wrapper">
          <div class="menuContent">
            <a href="/" class="logo">
              <img src="{% static 'assets/images/Logo.svg' %}" class="svg" />
            </a>
            <div class="outer">
              <div class="inner">
                <nav {% if request.user_agent.is_mobile %} style="max-width: 252px;" {% endif %}>
                  <ul>
                    <li>
                      <a href="{% url 'index' %}">
                        <div>Homepage</div>
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'product:all_product_list' %}">
                        <div>View Marketplace</div>
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'blog:blog_list' %}">
                        <div>Blogs</div>
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'case_study' %}">
                        <div>Case Studies</div>
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'contact_us' %}">
                        <div>Contact us</div>
                      </a>
                    </li>
                  </ul>
                  <div class="terms-links">
                    <a href="{% url 'privacy_policy' %}">
                      <div>Privacy Policy</div>
                    </a>
                    <a href="{% url 'terms_conditions' %}">
                      <div>Terms & Conditions</div>
                    </a>
                  </div>
                </nav>
              </div>
            </div>
          </div>
    
          <div class="newestTemplateWrapper">
            <div class="outer">
              <div class="inner">
                <div class="label">
                  <div></div>
                </div>
                <div class="templateImage">
                  <a href="#">
                    <img src="{% static 'uploads/product/74/6e1d7f0fa3e1e92dbb5c618c5349d4a7.png' %}" />
                  </a>
                </div>
                <a href="#" class="exploreBtn">
                  <div style="color: black;">Explore</div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    
    <!-- end -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.js"></script>
    <script src="{% static 'assets/js/slick-slider.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="{% static 'assets/220d0582/jquery.js' %}"></script>
    <script src="{% static 'assets/2e3e25d2/yii.js' %}"></script>
    <script src="{% static 'assets/js/fullpage-slider.js' %}"></script>
    <script src="{% static 'assets/js/svgcovert.js' %}"></script>
    <script src="{% static 'assets/js/ui.js' %}"></script>
    <script src="{% static 'assets/js/easing.js' %}"></script>

    <script src="{% static 'assets/js/cookie.js' %}"></script>
    <script src="{% static 'assets/js/isIE.js' %}"></script>
    <script src="{% static 'assets/js/moder.js' %}"></script>
    <script src="{% static 'assets/js/mobile.js' %}"></script>
    <script src="{% static 'assets/js/perfect-scrollbar.js' %}"></script>
    
    <script src="{% static 'assets/d44acf32/js/mainc047.js' %}"></script>

    {% block js %}

    {% endblock %}
</body>
</html>

templates/cart_ajax.html
{% load static %}
{% if cart_count == 0 %}
    <div class="cartWrapper">


        <div class="countWrapper empty">
            <div>
                Your Cart: Empty
            </div>
        </div>
        <div class="valign100h"></div>
    </div>
    {% else %}

    <div class="cartWrapper">



        <form id="cart-form" method="post" data-pjax>
            <input type="hidden" name="_csrf" value="TjMtV0hCdDQeXVkZCS5NdStxfwEwOhlsOwV8GicIMX8/eFthezcmQA==">
            <div class="countWrapper">
                <div>
                    Your Cart: {{ cart_count|floatformat:0 }} item{{ cart_count|pluralize }} </div>
            </div>
            <div class="itemsWrapper">
                <div>
                    {% for item in cart_items %}
                    <div class="item">
                        <div>
                            <div class="price">
                                ${{ item.product.product_price }} <span class="formattingPriceWrapper">{% if item.extra_charge != 0 %} + ${{ item.extra_charge }} {% endif %}</span>
                            </div>
                            <a href="{% url 'ecommerce_cart:remove-from-cart' item_id=item.id %}" class="removeBtn">
                                <img src="{% static 'assets/d44acf32/img/cross.svg' %}" class="svg">
                            </a>
                        </div>
                        <div class="imgWrapper">
                            <a href="{% url 'product:product_detail' product_slug=item.product.slug %}">
                                {% if item.product.image_1 %}
                                    <img src="{{ item.product.image_1.url }}">
                                {% else %}
                                    <img src="{% static 'uploads/product/66/7e9a6bc3d484a1dc4b3ce7bbff386016.png' %}">
                                {% endif %}
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="actionWrapper">
                <div class="total">
                    <div>
                        Total: <span>${{ cart_total }}</span>
                    </div>
                </div>
                <div class="btnWrapper">
                    <div>
                        <a href="{% url 'ecommerce_cart:check_out_address' %}" class="buyBtn">
                            Buy
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
    {% endif %}

    <div class="cartOverlay"></div>

templates/contact_us.html
{% extends "base.html" %} 
{% load static %} 

{% block title %} Contact US {% endblock %}

{% block content %}
<div class="mainWrapper">
    <section class="contact fullHeight">
        <div class="wrapper">
            <div class="infoBlock">
                <div class="inner">
                    <h1 class="title">
                        <div>
                            Contact us
                        </div>
                    </h1>
                    <div>
                        <div class="row">
                            <div>
                                <div class="label">
                                    Company:
                                </div>
                                <div class="text">
                                    BROWNFOLD Inc.<br>

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div>
                                <div class="label">
                                    Email:
                                </div>
                                <div class="text">
                                    <a href="mailto:support@brownfold.com">
                                        support@brownfold.com
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div>
                                <div class="label">
                                    Social networks:
                                </div>
                                <div class="text snWrapper">
                                    <a target="_blank" href="#">
                                        <img src="{% static 'assets/d44acf32/img/insta.svg' %}">
                                    </a>
                                    <a target="_blank" href="#">
                                        <img src="{% static 'assets/d44acf32/img/Facebook.svg' %}">
                                    </a>
                                    <a target="_blank" href="#">
                                        <img src="{% static 'assets/d44acf32/img/LinkedIn.svg' %}">
                                    </a>
                                    <a target="_blank" href="#">
                                        <img src="{% static 'assets/d44acf32/img/Shape.svg' %}">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- <a href="http://zipl.pro/" target="_blank" class="byZIPL">
                        <div>
                            <span>Created by</span>
                            <img src="assets/d44acf32/img/zipl.svg" class="svg">
                        </div>
                    </a> -->

                </div>
            </div>
            <div class="formBlock">
                <div class="inner">


                    <div id="w0">
                        <div class="label">
                            <div>
                                Write To us
                            </div>
                        </div>
                        <div class="formWrapper">

                            <form id="w1" method="POST"
                                data-pjax>
                                {% csrf_token %}

                                <div class="form-group field-feedbackform-name required">
                                    <label class="control-label" for="feedbackform-name">Name *</label>
                                    {{ form.name }}
						            {{ form.name.errors }}

                                    <p class="help-block help-block-error"></p>
                                </div>
                                <div class="form-group field-feedbackform-email required">
                                    <label class="control-label" for="feedbackform-email">Email *</label>
                                    {{ form.email }}
						            {{ form.email.errors }}

                                    <p class="help-block help-block-error"></p>
                                </div>
                                <div class="form-group field-feedbackform-message required">
                                    <label class="control-label" for="feedbackform-message">Note *</label>
                                    {{ form.message }}

                                    <p class="help-block help-block-error"></p>
                                </div>
                                {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                                <button type="submit" class="btn">Send</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/privacy_policy.html
{% extends "base.html" %} 
{% load static %} 

{% block title %} Contact US {% endblock %}

{% block content %}
<div class="mainWrapper">
    <div class="cvContent policy">
        <h1 class="title">
            Privacy Policy
        </h1>
        <div class="content">
            <p>Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to
                understand how we collect, use, communicate and disclose and make use of personal information. </p>
            <p>This privacy policy sets out how BROWNFOLD uses and protects any information that you
                provided. BROWNFOLD is devoted to ensuring that your privacy is protected. Should we ask you
                to provide certain information by which you can be identified when accessing your account
                information, you can be assured that such information will only be used in accordance with this
                privacy statement. BROWNFOLD has a firm policy of protecting the confidentiality and
                security of information that we collect from you. We do not share your non‐public personal
                information with unaffiliated third parties. </p>
            <p>Please read this policy carefully. It gives you important information about how we handle your
                personal information. BROWNFOLD reserves the right to change this policy at any time.</p>
            <p>This privacy notice discloses the privacy practices for www.brownfold.online. This privacy notice
                applies solely to information collected by this website.</p> <br />






            <h2>1. Information Collection, Use, And Sharing</h2>
            <p>We are the sole owners of the information collected on this site. We only have access to/collect
                information that you voluntarily give us via email or other direct contact from you. </p>
            <p>We will use your information to respond to you, regarding the reason you contacted us. We will not
                share your information with any third party outside of our organization. We may contact you via
                email in the future to tell you about specials, new products or services, or changes to this privacy
                policy.
            </p><br />


            <h2>2. Your Access To And Control Over Information</h2>
            <p>You may opt out of any future contacts from us at any time. You can do the following at any time by
                contacting us via the email address given on our website:


                • See what data we have about you, if any.<br />

                • Change/correct any data we have about you.<br />

                • Have us delete any data we have about you.<br />

                • Express any concern you have about our use of your data.</p><br />





            <h2>3. Security</h2>
            <p>We take precautions to protect your information. When you submit sensitive information via the
                website, your information is protected both online and offline. The information is encrypted and
                transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar
                and looking for "https" at the beginning of the address of the Web page.
                While we use encryption to protect sensitive information transmitted online, we also protect your
                information offline. Only employees who need the information to perform a specific job (for example,
                billing or customer service) are granted access to personally identifiable information. The
                computers/servers in which we store personally identifiable information are kept in a secure
                environment.</p><br />



            <h2>4. Changes To Privacy Policy</h2>
            <p>BROWNFOLD reserves the right to modify this privacy policy at any time. If we make changes
                that materially affect our uses or disclosures of personally identifiable information that we have
                previously collected, we will notify you here, by email, or by means of a notice on our homepage.
            </p><br />



            <h2>5. Contacting Us</h2>
            <p>If you have any questions or suggestions regarding our privacy policy, please contact us at
                support@brownfold.online</p>




        </div>
    </div>
</div>
{% endblock %}