blog/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views, views_admin
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [

    url(r'^$', views.BlogListView.as_view(), name='blog_list'),

    url(r'^(?P<blog_slug>[\w-]+)/$',
        views.blog_details_view, name='blogdetail'),

    url(r'^category/(?P<blog_category_slug>[\w-]+)/$',
        views.blog_categories_details, name='blog_category_details'),

    url(r'^tag/(?P<blog_tag_slug>[\w-]+)/$',
        views.blog_tag_details, name='blog_tag_details'),

    url(r'^search/item/$',
        views.search, name='search_blog'),


    #################### All ADMIN VIEWS ################################

    ############## BLOG CATEGORY VIEWS ######################

    url(r'^blog/category-list/admin/$', views_admin.BlogCategoriesAdminListView.as_view(), name='blog_category_list'),

    url(r'^blog/category-create/admin/$', views_admin.BlogCategoryCreateView.as_view(), name='blog_category_create'),

    url(r'^blog/category/(?P<blog_category_slug>[\w-]+)/update/admin/$', views_admin.BlogCategoryUpdateView.as_view(), name='blog_category_update'),

    url(r'^blog/category/(?P<blog_category_slug>[\w-]+)/delete/admin/$', views_admin.blog_category_delete_view, name='blog_category_delete'),


    ##################### Blog Views URL ##############################################

    url(r'^blog/list/admin/$', views_admin.BlogListViewAdmin.as_view(), name='blog_list_admin'),

    url(r'^blog/create/admin/$', views_admin.BlogCreateView.as_view(), name='blog_create_admin'),

    url(r'^blog/update/(?P<blog_slug>[\w-]+)/admin/$', views_admin.BlogUpdateView.as_view(), name='blog_update_admin'),

    url(r'^blog/delete/(?P<blog_pk>\d+)/admin/$', views_admin.delete_blog, name='blog_delete_admin'),


    ##################### Blog Tags URL #########################################

    url(r'^blog/tag-list/admin/$', views_admin.BlogTagsListView.as_view(), name='blog_tag_list_admin'),
    url(r'^blog/tag-create/admin/$', views_admin.BlogTagsCreateView.as_view(), name='blog_tag_create_admin'),

    url(r'^blog/tag/(?P<blog_tag_slug>[\w-]+)/update/admin/$', views_admin.BlogTagUpdateView.as_view(), name='blog_tag_update_admin'),

    url(r'^blog//tag/(?P<blog_tag_pk>\d+)/delete/admin/$', views_admin.delete_blog_tags, name='blog_tag_delete_admin'),

]

brown/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls import url, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.index, name='index'),
    path('contact-us', views.contact_us_view, name='contact_us'),

    path('privacy-policy', views.privacy_policy, name='privacy_policy'),

    path('terms-and-conditions', views.terms_conditions, name='terms_conditions'),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r"^our-products/", include("products.urls", namespace="product")),

    url(r"^ecommerce/", include("ecommerce_cart.urls", namespace="ecommerce_cart")),

    url(r"^blogs/", include("blog.urls", namespace="blog")),


    path('superadmin/', views.admin_index, name='admin_index'),
    url(r'^superadmin/contact-query/$', views.contact_query_view, name="contact_query"),
	url(r'^superadmin/contact-query/delete/(?P<query_pk>\d+)/$',
        views.delete_query, name='query_delete'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce_cart/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

app_name = 'ecommerce_cart'

urlpatterns = [
    url(r'^whislist/$', views.whislist_view, name='whislist_view'),

    url(r'^add-to-whislist/(?P<product_id>[-\w]+)/$',
        views.add_to_whislist, name="add_to_whislist"),

    url(r'^remove-from-whislist/(?P<product_id>[-\w]+)/$',
        views.remove_from_whislist, name="remove_from_whislist"),

    url(r'^add-to-cart/(?P<product_id>[-\w]+)/$',
        views.add_to_cart, name="add_to_cart"),

    url(r'^remove-from-cart/(?P<item_id>[-\w]+)/$',
        views.delete_from_cart, name="remove-from-cart"),

    url(r'^checkout/$', views.check_out_address, name='check_out_address'),

    url(r'^checkout/confirm/$', views.checkout_confirm_page, name='checkout_confirm_page'),

    url(r'^cart/page/$', views.cart_view, name='cart_view'),

    url(r'^cart/add/ajax/$', views.add_to_cart_ajax, name='add_to_cart_ajax'),

    url(r'^whislist/remove/ajax/$', views.remove_from_whislist_ajax, name='remove_from_whislist_ajax'),


    ##### Admin Urls #####

    url(r'^orders_list/admin/$',
        views.UserOrderListAdminView.as_view(), name='orders_list_admin'),

    url(r'^orders/(?P<user_order_pk>\d+)/admin/$',
        views.OrderDetailView.as_view(), name='orders_details_admin'),
]

products/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views, views_admin

app_name = 'products'

urlpatterns = [

    url(r'^list/$',views.all_product_list, name='all_product_list'),
    url(r'^category_wise_product/$',views.search_product_category_wise, name='search_product_category_wise'),

    url(r'^category_product_details/(?P<category_slug>[\w-]+)/$',
        views.product_category_details_view, name='product_category_details'),

    url(r'^(?P<product_slug>[\w-]+)/$',
        views.product_details_view, name='product_detail'),


    ##################### Views Admin #################################

    ######### Product Categories Url  ##################
    # url(r'^category/category-list/$',
    #     views_admin.AllCategoryListView.as_view(), name='category_list'),


    url(r'^product-category/admin/$',
        views_admin.ProductCategoryListView.as_view(), name='category_list'),

    url(r'^product-category/admin/create/$',
        views_admin.ProductCategoryCreateView.as_view(), name='category_create'),

    url(r'^product-category/(?P<category_pk>\d+)/admin/update/$',
        views_admin.ProductCategoryUpdateView.as_view(), name='category_update'),

    url(r'^product-category/(?P<category_pk>\d+)/admin/delete/$',
        views_admin.category_delete_view, name='category_delete'),

    ######### Product Url  ##################

    url(r'^product/admin/$',
        views_admin.ProductsListView.as_view(), name='product_list_admin'),

    url(r'^product/admin/create/$',
        views_admin.ProductCreateView.as_view(), name='product_create'),

    url(r'^product/(?P<product_slug>[\w-]+)/admin/update/$',
        views_admin.ProductUpdateView.as_view(), name='product_update'),

    url(r'^product/(?P<product_slug>[\w-]+)/admin/details/$',
        views_admin.product_details_view, name='product_details_admin'),

    url(r'^product/(?P<product_pk>\d+)/admin/delete/$',
        views_admin.delete_product, name='product_delete'),

]

ecommerce_cart/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db import transaction
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.db.models import Sum, Value, Count, FloatField, IntegerField
from django.views.generic import ListView, DetailView
from django.db.models.functions import Coalesce

from user_profile.models import *
from ecommerce_cart.models import *
from ecommerce_cart.extras import *
from products.models import *
from ecommerce_cart.forms import *

from app.common import *
# Create your views here.

def whislist_view(request):
    """
    WhisList View
    """
    try:
        device = request.COOKIES['device']
    except KeyError as error:
        device = None
    except Exception as exception:
        device = None

    customer = Customer.objects.filter(device=device).first()
    if not customer:
        created = Customer.objects.create(device=device)
        created.save()

    existing_orders = WhisList.objects.filter(
        customer=customer, is_carted=False)  # Getting Items in Cart


    context = {
        'existing_orders' : existing_orders,
    }
    return CommonMixin.render(request, 'whislist.html', context)


def add_to_whislist(request, **kwargs):
    """
    Add To Whislist View
    """
    product = Product.objects.filter(id=kwargs.get('product_id', "")).first()


    # if int(total_quantity) <= 0:
    #     messages.error(
    #         request, 'The Selected Product is Out Of Stock!')
    #     return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    try:
        device = request.COOKIES['device']
    except KeyError as error:
        print(error)
        device = None
    except Exception as exception:
        print(exception)
        device = None


    with transaction.atomic():

        customer = Customer.objects.filter(device=device).first()
        if not customer:
            created = Customer.objects.create(device=device)
            created.save()


        add_item = WhisList.objects.create(
            product=product, customer=customer, ref_code=generate_order_id(), is_carted=False)

        product.whislist_items.add(customer)
        product.save()

        add_item.save()

    messages.success(
        request, 'Selected Product is successfully added to wishlist')

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def remove_from_whislist(request, **kwargs):
    """
    Remove From Whislist View
    """
    product = Product.objects.filter(id=kwargs.get('product_id', "")).first()

    try:
        device = request.COOKIES['device']
    except KeyError as error:
        print(error)
        device = None
    except Exception as exception:
        print(exception)
        device = None


    with transaction.atomic():

        customer = Customer.objects.filter(device=device).first()
        if not customer:
            created = Customer.objects.create(device=device)
            created.save()


        WhisList.objects.filter(
            product=product, customer=customer).delete()

        product.whislist_items.remove(customer)
        product.save()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def add_to_cart(request, **kwargs):
    """
    Add To Cart View
    """
    product = Product.objects.filter(id=kwargs.get('product_id', "")).first()

    try:
        device = request.COOKIES['device']
    except KeyError as error:
        device = None
    except Exception as exception:
        device = None

    extra_charge = request.GET.get('extra_charge', 0)

    with transaction.atomic():

        customer = Customer.objects.filter(device=device).first()
        if not customer:
            created = Customer.objects.create(device=device)
            created.save()

        add_item = CartItems.objects.create(
            product=product, customer=customer, ref_code=generate_order_id(), extra_charge=extra_charge)

        add_item.save()

    messages.success(
        request, 'Selected Product is successfully added to cart')

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def delete_from_cart(request, item_id):
    """
    Delete One Item From Cart
    """
    item_to_delete = CartItems.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.success(
            request, 'Selected Product is successfully removed from cart')
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def check_out_address(request):
    """
    Check Out View
    """

    try:
        device = request.COOKIES['device']
    except KeyError as error:
        device = None
    except Exception as exception:
        device = None

    customer = Customer.objects.filter(device=device).first()
    if not customer:
        created = Customer.objects.create(device=device)
        created.save()

    if request.method == 'POST':
        address_form = AddressForm(request.POST or None)
        if address_form.is_valid():
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            state = request.POST.get('state')
            country = request.POST.get('country')
            phone_no = request.POST.get('phone_no')
            email = request.POST.get('email')
            notes = request.POST.get('notes')


            answer = Address.objects.create(customer=customer, first_name=first_name, last_name=last_name,\
                                             state=state, phone_no=phone_no, \
                                                country=country, email=email, notes=notes)
            check_out = AppliedAddress.objects.create(
                customer=customer, address=answer)

            answer.save()

            check_out.save()

            messages.success(request, 'Address Applied Successfully')
            return redirect(reverse('ecommerce_cart:checkout_confirm_page'))
    else:
        address_form = AddressForm()

    context = {
        'form' : address_form
    }
    return CommonMixin.render(request, "check_out_address.html", context)


def checkout_confirm_page(request):
    """
    Checkout Confirm Page
    """
    try:
        device = request.COOKIES['device']
    except KeyError as error:
        device = None
    except Exception as exception:
        device = None

    customer = Customer.objects.filter(device=device).first()
    if not customer:
        created = Customer.objects.create(device=device)
        created.save()
    
    applied_address = AppliedAddress.objects.filter(customer=customer).first()

    context = {
        'applied_address' : applied_address
    }
    return CommonMixin.render(request, "check_out_confirm.html", context)


def cart_view(request):
    """
    Cart Page
    """
    try:
        device = request.COOKIES['device']
    except KeyError as error:
        device = None
    except Exception as exception:
        device = None

    customer = Customer.objects.filter(device=device).first()
    if not customer:
        created = Customer.objects.create(device=device)
        created.save()
    

    context = {}
    return CommonMixin.render(request, "cart.html", context)


def add_to_cart_ajax(request):
    """
    Add to Cart Ajax View
    """
    extra_charge = request.GET.get('extra_charge', 0)
    product_id = request.GET.get('product_id', 0)

    try:
        device = request.COOKIES['device']
    except KeyError as error:
        device = None
    except Exception as exception:
        device = None

    with transaction.atomic():

        customer = Customer.objects.filter(device=device).first()
        if not customer:
            created = Customer.objects.create(device=device)
            created.save()

        add_item = CartItems.objects.create(
            product_id=product_id, customer=customer, ref_code=generate_order_id(), extra_charge=extra_charge)

        add_item.save()

    cart_items = CartItems.objects.filter(
            customer=customer, is_ordered=False)
    
    cart_total = cart_items.aggregate(
            the_sum=Coalesce(Sum('cart_total'), Value(0), output_field=IntegerField()))['the_sum']

    cart_count = cart_items.aggregate(
        the_sum=Coalesce(Count('id'), Value(0), output_field=FloatField()))['the_sum']  # Cart Item Count

    messages.success(
        request, 'Selected Product is successfully added to cart')
    
    context = {
        'customer' : customer,
        'cart_total' : cart_total,
        'cart_items' : cart_items,
        'cart_count' : cart_count
    }
    if request.is_ajax():
        html = render_to_string('cart_ajax.html',
                                context, request=request)

    data = {
        'html' : html
    }
    return JsonResponse(data)


def remove_from_whislist_ajax(request):
    """
    Remove From Whislist Ajax
    """
    product_id = request.GET.get('product_id', 0)

    try:
        device = request.COOKIES['device']
    except KeyError as error:
        print(error)
        device = None
    except Exception as exception:
        print(exception)
        device = None

    with transaction.atomic():

        product = Product.objects.filter(id=product_id).first()

        customer = Customer.objects.filter(device=device).first()
        if not customer:
            created = Customer.objects.create(device=device)
            created.save()

        WhisList.objects.filter(
            product=product, customer=customer).delete()

        product.whislist_items.remove(customer)
        product.save()

    cart_items = CartItems.objects.filter(
            customer=customer, is_ordered=False)
    
    cart_total = cart_items.aggregate(
            the_sum=Coalesce(Sum('cart_total'), Value(0), output_field=IntegerField()))['the_sum']

    cart_count = cart_items.aggregate(

ecommerce_cart/templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block title %} Cart View {% endblock %}

{% block content %}
<div class="checkoutWrapper">
    <div class="wrapper">

        <!-- <a href="/" class="closeCheckout">
            Close checkout page
            <img src="/assets/d44acf32/img/cross.svg" class="svg">
        </a> -->

        <h1 class="title">
            Cart View
        </h1>

        <!-- <nav>
            <a href="{% url 'ecommerce_cart:check_out_address' %}" class="disabled">
                Basic info
            </a>

            <a href="#" class="active">
                Confirmation
            </a>
        </nav> -->

    </div>


    <div class="wrapper confirmation">
        <div class="cartInfo">
            <div class="bigLabel">Your Carted Items:</div>
            <div class="items">
                {% for item in cart_items %}
                <div class="item">
                    <div class="aboutProduct">
                        <div class="index">{{ forloop.counter }}</div>
                        <div class="imgWrapper">
                            {% if item.product.image_1 %}
                                <img src="{{ item.product.image_1.url }}">
                            {% else %}
                                <img src="{% static 'uploads/product/79/005df54fba1b3826e4f1b7dc52ef6bce.png' %}">
                            {% endif %}
                        </div>
                        <div class="info">
                            {{ item.product.name }} </div>
                    </div>
                    <div class="price">${{ item.cart_total }}</div>
                </div>
                {% endfor %}
            </div>
            <div class="total">
                <div class="label">Total price:</div>
                <div class="value">${{ cart_total }}</div>
            </div>
        </div>
    </div>

    <div class="submitWrapper">
        <button type="button" class="btn" name="confirm" onclick="location.href='{% url 'ecommerce_cart:check_out_address' %}'">Buy</button>    
    </div>

</div>
{% endblock %}

ecommerce_cart/templates/check_out_confirm.html
{% extends "base.html" %}
{% load static %}

{% block title %} Checkout Confirm {% endblock %}

{% block content %}
<div class="checkoutWrapper">
    <div class="wrapper">

        <!-- <a href="/" class="closeCheckout">
            Close checkout page
            <img src="/assets/d44acf32/img/cross.svg" class="svg">
        </a> -->

        <h1 class="title">
            Checkout
        </h1>

        <nav>
            <a href="{% url 'ecommerce_cart:check_out_address' %}" class="disabled">
                Basic info
            </a>

            <a href="#" class="active">
                Confirmation
            </a>
        </nav>

    </div>


    <div class="wrapper confirmation">
        <div class="cartInfo">
            <div class="bigLabel">Your purchases:</div>
            <div class="items">
                {% for item in cart_items %}
                <div class="item">
                    <div class="aboutProduct">
                        <div class="index">{{ forloop.counter }}</div>
                        <div class="imgWrapper">
                            {% if item.product.image_1 %}
                                <img src="{{ item.product.image_1.url }}">
                            {% else %}
                                <img src="{% static 'uploads/product/79/005df54fba1b3826e4f1b7dc52ef6bce.png' %}">
                            {% endif %}
                        </div>
                        <div class="info">
                            {{ item.product.name }} </div>
                    </div>
                    <div class="price">${{ item.cart_total }}</div>
                </div>
                {% endfor %}
            </div>
            <div class="total">
                <div class="label">Total price:</div>
                <div class="value">${{ cart_total }}</div>
            </div>
        </div>
        <div class="userInfo">
            <div class="bigLabel">Your information:</div>
            <div class="info-row">
                <div class="label">First Name</div>
                <div class="value">{{ applied_address.address.first_name }}</div>
            </div>
            <div class="info-row">
                <div class="label">Last Name</div>
                <div class="value">{{ applied_address.address.last_name }}</div>
            </div>
            <div class="info-row">
                <div class="label">Email</div>
                <div class="value">{{ applied_address.address.email }}</div>
            </div>
            <div class="info-row">
                <div class="label">Phone</div>
                <div class="value">{{ applied_address.address.phone_no }}</div>
            </div>
            <div class="info-row">
                <div class="label">State</div>
                <div class="value">{{ applied_address.address.state }}</div>
            </div>
            <div class="info-row">
                <div class="label">Country</div>
                <div class="value">{{ applied_address.address.country }}</div>
            </div>
        </div>
    </div>

    <div class="submitWrapper">
        <button type="button" class="btn" name="confirm">Confirm</button>    
    </div>

</div>
{% endblock %}

ecommerce_cart/templates/whislist.html
{% extends "base.html" %}
{% load static %}

{% block title %} Whishlist {% endblock %}

{% block content %}

<div class="mainWrapper templatesWrapper wishlistWrapper">

    <div class="categoryTitle">
        <div class="rotateWrapper">
            <div class="name">
                <div>
                    Wishlist
                </div>
            </div>
        </div>
    </div>

    <div class="scrollHint">
        <div class="rotateWrapper">
            <div>
                Scroll down
            </div>
        </div>
    </div>

    <section class="templatesList">
        <div class="wrapper">
            <div id="whislist-item">
                {% include 'whislist_ajax_list.html' %}
            </div>
        </div>
    </section>

</div>

{% endblock %}


{% block js %}

<script type="text/javascript">
    
    function update_anchor(id)
    {
        var link = document.getElementById("cart_link");
        link.setAttribute("onclick", "add_to_cart(" + id + ", 0)");

        var checkBox = document.getElementById("formatting_cb");
        checkBox.setAttribute("data", id);
    } 
  </script>

  <script>
    function update_final_link() {
        var checkBox = document.getElementById("formatting_cb");
        var url = document.getElementById("cart_link");

        var extra_charge = checkBox.getAttribute("data")
        var id_int = parseInt(extra_charge)
        console.log(id_int)

        if (checkBox.checked == true){
            url.setAttribute("onclick", "add_to_cart(" + id_int + ", " + 25 + ")");
        } else {
            url.setAttribute("onclick", "add_to_cart(" + id_int + ", 0)");
        }
    }
  </script>


  <script>
    function update_link()
    {
        document.getElementById("show_notify_cart").style.display = "none";
        document.body.classList.add("showCart"); 
    }
    function add_to_cart(product_id, extra_charge) {
        $.ajax({
            url: '{% url "ecommerce_cart:add_to_cart_ajax" %}',
            data: {
                'product_id' : product_id,
                'extra_charge' : extra_charge,
            },
            dataType: 'json',
            success: function (response) {
                $('#cart_content').html(response['html']);
                document.getElementById("cart_popup").style.display = "none"; 
                document.getElementById("show_notify_cart").style.display = "unset"; 
                document.getElementById("show_notify_cart").innerHTML = "<div>Selected Product Successfully Added to Cart!</div>";
                setTimeout(update_link, 2000);

            },
            error: function (rs, e) {
                console.log(rs);
                console.log(e)
            }
        });

    }
  </script>


<script>
    function remove_from_whislist(product_id) {
        $.ajax({
            url: '{% url "ecommerce_cart:remove_from_whislist_ajax" %}',
            data: {
                'product_id' : product_id,
            },
            dataType: 'json',
            success: function (response) {
                $('#whislist-item').html(response['html']);
            },
            error: function (rs, e) {
                console.log(rs);
                console.log(e)
            }
        });

    }
</script>

{% endblock %}

ecommerce_cart/templates/whislist_ajax_list.html
{% load static %}

<div class="templatesListWrapper">
    <div id="w0">
        <div id="w1" class="list-view">
            {% for obj in existing_orders %}
                <div class="item templateItem" data-key="{{ obj.id }}">

                    <div class="imgWrapper">
                        <div class="imgBlock">
                            <a href="{% url 'product:product_detail' product_slug=obj.product.slug %}" class="toProfile">
                                {% if obj.product.image_1 %}
                                    <img src="{{ obj.product.image_1.url }}"
                                        alt="Tempalte 1"> 
                                {% else %}
                                    <img src="{% static 'uploads/product/66/7e9a6bc3d484a1dc4b3ce7bbff386016.png' %}"
                                        alt="Tempalte 1"> 
                                {% endif %}
                            </a>
                            <a class="toCartBtn" href="{% url 'ecommerce_cart:add_to_cart' product_id=obj.product.id %}" data-formatting="{{ obj.product.product_price }}"
                                    onclick="update_anchor({{ obj.product.id }})"
                                {% if obj.product.image_1 %} 
                                    data-img="{{ obj.product.image_1.url }}"
                                {% else %}
                                    data-img="{% static 'uploads/product/66/7e9a6bc3d484a1dc4b3ce7bbff386016.png' %}"
                                {% endif %}
                                data-title="{{ obj.product.name }}" data-price="$35.00" data-formatting-html="$150.00">Add
                                to cart</a>  <a
                                class="no_whislist" href="#" onclick="remove_from_whislist({{ obj.product.id }})"><img
                                    src="{% static 'assets/d44acf32/img/like_cross.svg' %}" class="svg "></a>
                        </div>
                    </div>
                    <div class="allInfoWrapper">
                        <div class="categories">
                            <a href="templates481e.html?c=4">
                                {{ obj.product.category.name }} </a>
                        </div>
                        <a href="{% url 'product:product_detail' product_slug=obj.product.slug %}" class="title">
                            {{ obj.product.name }}</a>
                        <div class="infoWrapper">
                            <div class="ratingWrapper">
                                <div class="label">
                                    Rating:
                                </div>
                                <div class="rating">
                                    <span class=""></span>
                                    <span class=""></span>
                                    <span class="active"></span>
                                    <span class=""></span>
                                    <span class=""></span>
                                </div>
                            </div>
                            <div class="priceWrapper">
                                <div class="label currency">
                                    USD
                                </div>
                                <div class="value">
                                    ${{ obj.product.product_price }} </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
        </div>
    </div>
</div>